fix job

diff --git a/packages/devlake/dev/mysql-init-job.yaml b/packages/devlake/dev/mysql-init-job.yaml
--- a/packages/devlake/dev/mysql-init-job.yaml
+++ b/packages/devlake/dev/mysql-init-job.yaml
@@ -30,6 +30,19 @@ spec:
           - /bin/bash
           - -c
           - |
+            check_secret_exists() {
+              kubectl get secrets -o custom-columns=NAME:.metadata.name | grep -q "^devlake-mysql.*cluster-mysql-connection$"
+              return $?
+            }
+
+            echo "Waiting for the MySQL connection secret to be created..."
+            while ! check_secret_exists; do
+              sleep 5
+              echo "Secret not found, retrying in 5 seconds..."
+            done
+
+            echo "MySQL connection secret found. Proceeding with the job..."
+
             CONN_SECRET_NAME=$(kubectl get secrets -o custom-columns=NAME:.metadata.name | grep "^devlake-mysql.*cluster-mysql-connection$")
             endpoint=$(kubectl get secret $CONN_SECRET_NAME -n crossplane-system -o jsonpath='{.data.endpoint}' | base64 --decode)
             kubectl create service externalname devlake-mysql-service --external-name=$endpoint -n devlake --dry-run=client -o yaml | kubectl apply -f -
